# Generated by Django 5.2.6 on 2025-09-13 06:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('thumbnail', models.URLField()),
                ('category', models.CharField(choices=[('ball', 'Ball'), ('shoes', 'Shoes'), ('racket', 'racket'), ('safety', 'Safety')], default='', max_length=20)),
                ('stock', models.IntegerField(default=0)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
