# Generated by Django 5.2.6 on 2025-09-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('ball', 'Ball'), ('shoes', 'Shoes'), ('racket', 'Racket'), ('safety', 'Safety')], default='', max_length=20),
        ),
    ]
