# Generated by Django 5.2.6 on 2025-09-26 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_product_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
                ("brand", models.CharField()),
                ("stock", models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
