# Generated by Django 5.2.6 on 2025-09-30 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_car_alter_product_price_alter_product_stock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
