# Generated by Django 5.2.7 on 2025-10-07 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_product_created_at_product_views"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="thumbnail",
            field=models.URLField(blank=True),
        ),
    ]
