# Generated by Django 5.2.7 on 2025-10-08 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_product_thumbnail"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="product",
            name="views",
        ),
        migrations.AlterField(
            model_name="product",
            name="thumbnail",
            field=models.URLField(),
        ),
    ]
